use_default_settings: true

server:
  secret_key: "CHANGE_ME_32_CHARS_1234567890123"
  base_url: http://searxng:8080/
  image_proxy: true
  method: GET
  default_output_format: json
  public_instance: false
  trusted_proxies:
    - 172.0.0.0/12

ui:
  static_use_hash: true

redis:
  url: redis://searxng-redis:6379/0

search:
  safe_search: 0
  autocomplete: "duckduckgo"

auth:
  query_tokens:
    - "d2734b688f4d698aa861c2f404234e38fda6ae4a7e57c33e192bde49cf1ad8cd"

botdetection:
  enabled: false
